@startuml
actor Tester
participant TestRunner
participant MetaboCycle
participant GoalUpdater
Tester -> TestRunner: run_tests()
TestRunner -> MetaboCycle: run_metabo_cycle(input)
MetaboCycle --> TestRunner: result
TestRunner -> GoalUpdater: update_goal()
GoalUpdater --> TestRunner: new goal
TestRunner --> Tester: report
@enduml
